import type {
  AnalysisListItemResponse,
  AnalysisRequestDetailResponse,
  AnalysisRequestResponse,
  GenerateDesignRequest,
  TriggerStatusResponse,
} from "../analysis.types";

/**
 * Mock Design Generation Data Layer
 * Simulates backend API responses for design generation analysis requests
 * Used when VITE_USE_MOCK_DATA=true
 */

export const mockAnalysisRequestResponse: AnalysisRequestResponse = {
  _id: "analysis-001",
  project_id: "proj-001",
  category_name: "Dresses",
  status: "COMPLETED",
  created_at: "2026-05-08T10:00:00Z",
  updated_at: "2026-05-08T10:03:00Z",
  ai_job_id: "mock-job-001",
  ai_callback_raw: {
    job_id: "mock-job-001",
    request_id: "analysis-001",
    status: "COMPLETED",
    created_at: "2026-05-08T10:00:00Z",
    updated_at: "2026-05-08T10:03:00Z",
    started_at: "2026-05-08T10:00:30Z",
    finished_at: "2026-05-08T10:03:00Z",
    generated_designs: [],
    error: "",
  },
};

const analysisAttempts = new Map<string, number>();
const generationAttempts = new Map<string, number>();

/**
 * Mock design results that would be generated by AI
 * These are displayed in the ResultsGrid component
 */
export const mockDesignResults = [
  {
    id: "design-001",
    requestId: "analysis-001",
    imageUrl:
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=60",
    title: "Avant-Garde Summer Flow",
    description:
      "Y2K inspired dress with asymmetrical hemline and bold color blocking",
  },
  {
    id: "design-002",
    requestId: "analysis-001",
    imageUrl:
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=800&auto=format&fit=crop&q=60",
    title: "Urban Chic Evening Wear",
    description:
      "Minimalist utility dress with oversized pockets and techwear elements",
  },
  {
    id: "design-003",
    requestId: "analysis-001",
    imageUrl:
      "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=60",
    title: "Minimalist Eco-friendly Dress",
    description:
      "Sustainable fabric dress with monochrome color palette and clean lines",
  },
  {
    id: "design-004",
    requestId: "analysis-001",
    imageUrl:
      "https://images.unsplash.com/photo-1595777707802-41cefc7e7f45?w=800&auto=format&fit=crop&q=60",
    title: "Cottagecore Dream Collection",
    description:
      "Floral romantic dress with vintage inspirations and flowing silhouette",
  },
];

/**
 * Mock service for design generation/analysis API
 * Simulates backend API calls with realistic response data
 */
export const analysisMockService = {
  /**
   * Create a new analysis request and trigger design generation
   * @param data - Analysis request data (project_id, category, styles, trends)
   * @returns Promise of AnalysisRequestResponse with PENDING status
   */
  createAnalysisRequest: async (data: {
    project_id: string;
    category_name: string;
  }): Promise<AnalysisRequestResponse> => {
    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 500));

    return {
      _id: `analysis-${Date.now()}`,
      project_id: data.project_id,
      category_name: data.category_name,
      status: "PENDING",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      ai_job_id: "mock-job-pending",
      ai_callback_raw: {
        job_id: "mock-job-pending",
        request_id: data.project_id,
        status: "PENDING",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        started_at: "",
        finished_at: "",
        generated_designs: [],
        error: "",
      },
    };
  },

  /**
   * Poll for analysis request status (simulates async AI processing)
   * @param requestId - Analysis request ID to check
   * @param attempt - Attempt number for simulating progressive status updates
   * @returns Promise of updated AnalysisRequestResponse
   */
  getAnalysisStatus: async (
    requestId: string,
    attempt?: number
  ): Promise<AnalysisRequestResponse> => {
    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 300));

    // Simulate status progression: PENDING → PROCESSING → COMPLETED
    const currentAttempt =
      attempt ?? (analysisAttempts.get(requestId) || 0);
    analysisAttempts.set(requestId, currentAttempt + 1);

    let status: AnalysisRequestResponse["status"] = "PENDING";
    if (currentAttempt >= 1) status = "PROCESSING";
    if (currentAttempt >= 2) status = "COMPLETED";

    return {
      ...mockAnalysisRequestResponse,
      _id: requestId,
      status,
      result_images:
        status === "COMPLETED"
          ? mockDesignResults.map((design) => design.imageUrl)
          : [],
      updated_at: new Date().toISOString(),
    };
  },

  /**
   * Fetch design generation results
   * @param requestId - Analysis request ID
   * @returns Promise of design results array
   */
  getDesignResults: async (
    requestId: string
  ): Promise<typeof mockDesignResults> => {
    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 400));

    // In real implementation, this would fetch actual AI-generated images
    // For now, return mock results with consistent IDs based on request
    return mockDesignResults.map((design, index) => ({
      ...design,
      id: `${requestId}-design-${index}`,
      requestId,
    }));
  },

  /**
   * Trigger AI generation for an analysis request
   * @param requestId - Analysis request ID to generate for
   * @returns Promise of updated AnalysisRequestResponse
   */
  triggerGeneration: async (
    requestId: string,
    data: GenerateDesignRequest
  ): Promise<AnalysisRequestResponse> => {
    void data;
    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 800));

    return {
      ...mockAnalysisRequestResponse,
      _id: requestId,
      ai_job_id: `mock-generation-${requestId}`,
      status: "PENDING",
      updated_at: new Date().toISOString(),
    };
  },

  getTriggerStatus: async (
    requestId: string
  ): Promise<TriggerStatusResponse[]> => {
    await new Promise((resolve) => setTimeout(resolve, 300));

    const currentAttempt = generationAttempts.get(requestId) || 0;
    generationAttempts.set(requestId, currentAttempt + 1);

    let status: TriggerStatusResponse["status"] = "PENDING";
    if (currentAttempt >= 1) status = "PROCESSING";
    if (currentAttempt >= 2) status = "COMPLETED";

    return [
      {
        _id: `generated-${requestId}`,
        request_id: requestId,
        design_image_url:
          status === "COMPLETED"
            ? mockDesignResults.map((design) => design.imageUrl)
            : [],
        user_rating: 0,
        created_at: new Date().toISOString(),
        status,
      },
    ];
  },

  getListAnalysisByProject: async (
    projectId: string
  ): Promise<AnalysisListItemResponse[]> => {
    await new Promise((resolve) => setTimeout(resolve, 300));

    return [0, 1, 2].map((offset) => ({
      project_id: projectId,
      category_name: offset === 0 ? "Vest Nam" : "Dresses",
      _id: `analysis-history-${projectId}-${offset}`,
      status: offset === 2 ? "PROCESSING" : "COMPLETED",
      created_at: new Date(Date.now() - offset * 3600000).toISOString(),
      updated_at: new Date(Date.now() - offset * 1800000).toISOString(),
    }));
  },

  getAnalysisRequest: async (
    requestId: string
  ): Promise<AnalysisRequestDetailResponse> => {
    await new Promise((resolve) => setTimeout(resolve, 300));

    return {
      _id: requestId,
      project_id: requestId.split("-").slice(2, -1).join("-") || "proj-001",
      category_name: "Vest Nam",
      status: "COMPLETED",
      created_at: new Date(Date.now() - 3600000).toISOString(),
      updated_at: new Date().toISOString(),
      base_img_url: mockDesignResults[0]?.imageUrl,
      ai_job_id: `mock-job-${requestId}`,
      result_images: mockDesignResults.map((design) => design.imageUrl),
    };
  },

  /**
   * Delete an analysis request
   * @param requestId - Analysis request ID to delete
   * @returns Promise of success status
   */
  deleteAnalysisRequest: async (
    _requestId: string
  ): Promise<{ success: boolean }> => {
    // Simulate network delay
    console.log(_requestId);
    await new Promise((resolve) => setTimeout(resolve, 300));
    return { success: true };
  },
};
