import type { AnalysisRequestResponse } from "../analysis.types";

/**
 * Mock Design Generation Data Layer
 * Simulates backend API responses for design generation analysis requests
 * Used when VITE_USE_MOCK_DATA=true
 */

export const mockAnalysisRequestResponse: AnalysisRequestResponse = {
  _id: "analysis-001",
  project_id: "proj-001",
  category_name: "Dresses",
  status: "COMPLETED",
  created_at: "2026-05-08T10:00:00Z",
  updated_at: "2026-05-08T10:03:00Z",
};

/**
 * Mock design results that would be generated by AI
 * These are displayed in the ResultsGrid component
 */
export const mockDesignResults = [
  {
    id: "design-001",
    imageUrl:
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=60",
    title: "Avant-Garde Summer Flow",
    description:
      "Y2K inspired dress with asymmetrical hemline and bold color blocking",
  },
  {
    id: "design-002",
    imageUrl:
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=800&auto=format&fit=crop&q=60",
    title: "Urban Chic Evening Wear",
    description:
      "Minimalist utility dress with oversized pockets and techwear elements",
  },
  {
    id: "design-003",
    imageUrl:
      "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=60",
    title: "Minimalist Eco-friendly Dress",
    description:
      "Sustainable fabric dress with monochrome color palette and clean lines",
  },
  {
    id: "design-004",
    imageUrl:
      "https://images.unsplash.com/photo-1595777707802-41cefc7e7f45?w=800&auto=format&fit=crop&q=60",
    title: "Cottagecore Dream Collection",
    description:
      "Floral romantic dress with vintage inspirations and flowing silhouette",
  },
];

/**
 * Mock service for design generation/analysis API
 * Simulates backend API calls with realistic response data
 */
export const analysisMockService = {
  /**
   * Create a new analysis request and trigger design generation
   * @param data - Analysis request data (project_id, category, styles, trends)
   * @returns Promise of AnalysisRequestResponse with PENDING status
   */
  createAnalysisRequest: async (data: {
    project_id: string;
    category_name: string;
  }): Promise<AnalysisRequestResponse> => {
    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 500));

    return {
      _id: `analysis-${Date.now()}`,
      project_id: data.project_id,
      category_name: data.category_name,
      status: "PENDING",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };
  },

  /**
   * Poll for analysis request status (simulates async AI processing)
   * @param requestId - Analysis request ID to check
   * @param attempt - Attempt number for simulating progressive status updates
   * @returns Promise of updated AnalysisRequestResponse
   */
  getAnalysisStatus: async (
    requestId: string,
    attempt: number = 0
  ): Promise<AnalysisRequestResponse> => {
    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 300));

    // Simulate status progression: PENDING → PROCESSING → COMPLETED
    let status: "PENDING" | "COMPLETED" | "FAILED" = "PENDING";
    if (attempt >= 1) status = "PENDING";
    if (attempt >= 2) status = "COMPLETED";

    return {
      ...mockAnalysisRequestResponse,
      _id: requestId,
      status,
      updated_at: new Date().toISOString(),
    };
  },

  /**
   * Fetch design generation results
   * @param requestId - Analysis request ID
   * @returns Promise of design results array
   */
  getDesignResults: async (
    requestId: string
  ): Promise<typeof mockDesignResults> => {
    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 400));

    // In real implementation, this would fetch actual AI-generated images
    // For now, return mock results with consistent IDs based on request
    return mockDesignResults.map((design, index) => ({
      ...design,
      id: `${requestId}-design-${index}`,
    }));
  },

  /**
   * Trigger AI generation for an analysis request
   * @param requestId - Analysis request ID to generate for
   * @returns Promise of updated AnalysisRequestResponse
   */
  triggerGeneration: async (
    requestId: string
  ): Promise<AnalysisRequestResponse> => {
    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 800));

    return {
      ...mockAnalysisRequestResponse,
      _id: requestId,
      status: "PENDING",
      updated_at: new Date().toISOString(),
    };
  },

  /**
   * Delete an analysis request
   * @param requestId - Analysis request ID to delete
   * @returns Promise of success status
   */
  deleteAnalysisRequest: async (
    _requestId: string
  ): Promise<{ success: boolean }> => {
    // Simulate network delay
    console.log(_requestId);
    await new Promise((resolve) => setTimeout(resolve, 300));
    return { success: true };
  },
};
